# Generated by Django 4.2.6 on 2024-07-06 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='org_id',
            new_name='id',
        ),
    ]
